api:
  dashboard: true
  insecure: true  # Allows dashboard on :8080 without auth (or set to false and use the labels)

entryPoints:
  websecure:
    address: ":443"   # Your HTTPS services

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@a0a0.org
      storage: /acme/acme.json
      dnsChallenge:
        provider: linode
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: backend_storage

log:
  level: WARN

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  filters:
    statusCodes:
      - "200"
      - "400-404"
      - "500-503"
  fields:
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Authorization: drop
