services:
  arcane:
    image: ghcr.io/getarcaneapp/arcane:latest
    container_name: arcane
    env_file:
      - /mnt/zpool/Docker/Secrets/arcane.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/zpool/Docker/Stacks/arcane:/app/data
      - /mnt/zpool/Docker/Projects:/app/data/projects
      - /mnt/zpool/Docker/Stacks:/app/data/stacks
      - /mnt/zpool/Docker/Secrets:/mnt/zpool/Docker/Secrets:ro
    networks:
      - backend_storage
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=backend_storage"
      - "traefik.http.routers.arcane.rule=Host(`arcane.${DOMAIN}`)"
      - "traefik.http.routers.arcane.entrypoints=websecure"
      - "traefik.http.routers.arcane.tls.certresolver=letsencrypt"
      - "traefik.http.services.arcane.loadbalancer.server.port=3552"
    restart: unless-stopped

networks:
  backend_storage:
    external: true
