version: "3"

networks:
  backend_media:
    external: true

services:
  #
  # ==================================================================================
  # 13ft Ladder: Self-hosted paywall bypass for news articles
  # https://github.com/wasi-master/13ft
  #
  ladder:
    image: ghcr.io/wasi-master/13ft:latest
    container_name: ladder
    restart: unless-stopped
    networks:
      - backend_media
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=backend_media"
      - "traefik.http.routers.ladder.rule=Host(`${LADDER_HOST}.${DOMAIN}`)"
      - "traefik.http.routers.ladder.entrypoints=websecure"
      - "traefik.http.routers.ladder.tls.certresolver=letsencrypt"
      - "traefik.http.services.ladder.loadbalancer.server.port=5000"