---
networks:
  backend_media:
    external: true  # Tell Docker this network already exists

services:
  jellyfin:
    image: 'jellyfin/jellyfin:latest'
    restart: unless-stopped
    container_name: jellyfin
    networks:
      - backend_media
    env_file:
      - .env
    volumes:
      - ${DOCKER_ROOT}/Stacks/jellyfin/config:/config
      - ${DOCKER_ROOT}/Stacks/jellyfin/cache:/cache
      #
      - ${MEDIA_ROOT}/movies:/media/movies
      - ${MEDIA_ROOT}/music:/media/music
      - ${MEDIA_ROOT}/series:/media/series
      - ${MEDIA_ROOT}/music-lessons:/media/music-lessons
      #
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=backend_media"
      - "traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_HOST}.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"