---
networks:
  backend_media:
    external: true  # Tell Docker this network already exists

services:
  jellyfin:
    image: 'jellyfin/jellyfin:latest'
    restart: unless-stopped
    container_name: jellyfin
    networks:
      - backend_media
    volumes:
      - ${DOCKER_ROOT}/Stacks/jellyfin/config:/config
      - ${DOCKER_ROOT}/Stacks/jellyfin/cache:/cache
      - ${MEDIA_ROOT}/Movies:/jellyfin-movies
      - ${MEDIA_ROOT}/Music:/jellyfin-music
      - ${MEDIA_ROOT}/Series:/jellyfin-series
      - ${MEDIA_ROOT}/Music-Lessons:/jellyfin/music-lessons
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=backend_media"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"