---
networks:
  backend_media:
    external: true

services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    restart: unless-stopped
    networks:
      - backend_media
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${_BASE}/Docker/Stacks/freshrss:/config'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=backend_media"
      - "traefik.http.routers.freshrss.rule=Host(`rss.${DOMAIN}`)"
      - "traefik.http.routers.freshrss.entrypoints=websecure"
      - "traefik.http.routers.freshrss.tls.certresolver=letsencrypt"
      - "traefik.http.services.freshrss.loadbalancer.server.port=80"