---
networks:
  backend_storage:
    external: true  # Tell Docker this network already exists

services:
  minio:
    image: minio/minio
    container_name: minio
    networks:
      - backend_storage
    volumes:
      - ${DOCKER_ROOT}/Stacks/minio:/data # Persistent storage for MinIO data
    command: server /data --console-address ":9001"
    env_file:
      - ${DOCKER_ROOT}/Secrets/minio.env
    labels:
      - "traefik.enable=true"
      # API endpoint
      - "traefik.http.routers.minio-api.rule=Host(`${MINIO_API_HOST}.${DOMAIN}`)"
      - "traefik.http.routers.minio-api.entrypoints=websecure"
      - "traefik.http.routers.minio-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.minio-api.service=minio-api"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"
      # Console
      - "traefik.http.routers.minio-console.rule=Host(`${MINIO_CONSOLE_HOST}.${DOMAIN}`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls.certresolver=letsencrypt"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"